### ISSUE TITLE
Twitter login consistently bombs out

### ISSUE THREAD

**Issue by MariusVolkhart** [TruckMuncher/TruckMuncher-Android#58]
```java
02-07 12:47:30.666  27745-27745/com.truckmuncher.app.debug E/Twitter﹕ Invalid json: Failed to validate oauth signature and token
    com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 9 path $
            at com.google.gson.JsonParser.parse(JsonParser.java:65)
            at com.google.gson.JsonParser.parse(JsonParser.java:45)
            at com.twitter.sdk.android.core.TwitterApiException.parseApiError(TwitterApiException.java:119)
            at com.twitter.sdk.android.core.TwitterApiException.readApiError(TwitterApiException.java:108)
            at com.twitter.sdk.android.core.TwitterApiException.<init>(TwitterApiException.java:41)
            at com.twitter.sdk.android.core.TwitterApiException.convert(TwitterApiException.java:93)
            at com.twitter.sdk.android.core.Callback.failure(Callback.java:28)
            at retrofit.CallbackRunnable$2.run(CallbackRunnable.java:53)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
     Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 9 path $
            at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1573)
            at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1423)
            at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:546)
            at com.google.gson.stream.JsonReader.peek(JsonReader.java:429)
            at com.google.gson.JsonParser.parse(JsonParser.java:60)
            at com.google.gson.JsonParser.parse(JsonParser.java:45)
            at com.twitter.sdk.android.core.TwitterApiException.parseApiError(TwitterApiException.java:119)
            at com.twitter.sdk.android.core.TwitterApiException.readApiError(TwitterApiException.java:108)
            at com.twitter.sdk.android.core.TwitterApiException.<init>(TwitterApiException.java:41)
            at com.twitter.sdk.android.core.TwitterApiException.convert(TwitterApiException.java:93)
            at com.twitter.sdk.android.core.Callback.failure(Callback.java:28)
            at retrofit.CallbackRunnable$2.run(CallbackRunnable.java:53)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
02-07 12:47:30.669  27745-27745/com.truckmuncher.app.debug E/Twitter﹕ Failed to get request token
    com.twitter.sdk.android.core.TwitterApiException: 401 Authorization Required
            at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:388)
            at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220)
            at retrofit.RestAdapter$RestHandler$2.obtainResponse(RestAdapter.java:278)
            at retrofit.CallbackRunnable.run(CallbackRunnable.java:42)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at retrofit.Platform$Android$2$1.run(Platform.java:142)
            at java.lang.Thread.run(Thread.java:818)
02-07 12:47:30.706  27745-27745/com.truckmuncher.app.debug E/Twitter﹕ Authorization completed with an error
    com.twitter.sdk.android.core.TwitterAuthException: Failed to get request token
            at com.twitter.sdk.android.core.identity.OAuthController$1.failure(OAuthController.java:78)
            at com.twitter.sdk.android.core.internal.oauth.OAuth1aService$1.failure(OAuth1aService.java:215)
            at com.twitter.sdk.android.core.Callback.failure(Callback.java:28)
            at retrofit.CallbackRunnable$2.run(CallbackRunnable.java:53)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
02-07 12:47:30.708  27745-27745/com.truckmuncher.app.debug E/LoginFragment﹕ Twitter login failed: Failed to get request token
    com.twitter.sdk.android.core.TwitterAuthException: Failed to get request token
            at com.twitter.sdk.android.core.identity.OAuthController$1.failure(OAuthController.java:78)
            at com.twitter.sdk.android.core.internal.oauth.OAuth1aService$1.failure(OAuth1aService.java:215)
            at com.twitter.sdk.android.core.Callback.failure(Callback.java:28)
            at retrofit.CallbackRunnable$2.run(CallbackRunnable.java:53)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

**Comment by MariusVolkhart** [comment]
This seems to only happen in debug. Perhaps it's a configuration issue with our app.

@nockertsb any ideas?
